table Atualização
	lineageTag: fced78d8-3b71-493c-bf0d-2d63d6bff8d4

	measure 'Última Atualização Base' = ```
			
			MAX ( 'Atualização'[Última Atualização])
			
			```
		formatString: General Date
		lineageTag: 2767de08-696c-4512-9e7c-2a9681f08203

	column 'Última Atualização'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e9761b8-387b-44d0-af49-03245a90f28a
		summarizeBy: none
		sourceColumn: Última Atualização

		variation Variation
			isDefault
			relationship: c932241a-80fa-4c5a-af0f-756a206b5b88
			defaultHierarchy: LocalDateTable_87eb474c-d1ac-4f79-ba51-cf680bdfff69.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Atualização = m
		mode: import
		source =
				let
				    DataHoraAtualizacao = DateTimeZone.FixedUtcNow(),
				    ConverterParaLocal = DateTimeZone.ToLocal(DataHoraAtualizacao),
				    RemoverFuso = DateTimeZone.RemoveZone(ConverterParaLocal),
				    Tabela = #table(
				        {"Última Atualização"},
				        {{RemoverFuso}}
				    ),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"Última Atualização", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

